### ISSUE TITLE
please add image classification example

### ISSUE THREAD

**Issue by Emon526** [tensorflow/flutter-tflite#10]

**Comment by Alexi-Zemcov** [comment]
Hello @Emon526 
In [this PR ](https://github.com/am15h/tflite_flutter_helper/pull/72) i made the old good example work again.

This PR is not for a merge. It is rather to share a working example. So you can just download it [from my fork](https://github.com/Alexi-Zemcov/tflite_flutter_helper/tree/fix/replace_example/example/image_classification).

It still has a lot of legacy code and I'd like to refactor it in the future, but for now.

**Comment by Emon526** [comment]
thanks a lot @Alexi-Zemcov but the author of tflite_flutter_helper mentioned not to use the package because the package is discontinued.i am looking for a alternative solution

**Comment by JSYRD** [comment]
Hello @Emon526 ,
Are you trying to build tensors without using the package tflite_flutter_helper? I have some experience in making it.

**Comment by PaulTR** [comment]
Got it. So this is definitely an example that I'd like to have together once everything is up to date, but in the meantime the logic should be close-ish to [this Android sample](https://github.com/tensorflow/examples/blob/master/lite/examples/image_classification/android_play_services/app/src/kotlin/kotlin/org/tensorflow/lite/examples/classification/playservices/ImageClassificationHelper.kt).

As for the helper, the plan is to put something together that does exactly what that did, but with a richer feature set, via [MediaPipe](https://developers.google.com/mediapipe/solutions/vision/image_classifier). By all means if you need a solution _right now_ then the helper is still a solid option that'll get the job done with a bit of work into it (what Alexi did as an example) :)

**Comment by Alexi-Zemcov** [comment]
By the way, I faced into the problem described in this comment.
https://github.com/am15h/tflite_flutter_plugin/issues/133#issuecomment-1118419145

My .tflite model accepts the required grayscale image data in **one** channel. But in fact, as the `tfLiteTensorByteSize` method shows, I have **4 times** more data.

Does anyone have any ideas what to do with this?

**Comment by JSYRD** [comment]
> By the way, I faced into the problem described in this comment. [am15h/tflite_flutter_plugin#133 (comment)](https://github.com/am15h/tflite_flutter_plugin/issues/133#issuecomment-1118419145)
> 
> My .tflite model accepts the required grayscale image data in **one** channel. But in fact, as the `tfLiteTensorByteSize` method shows, I have **4 times** more data.
> 
> Does anyone have any ideas what to do with this?

Nice to meet you again, and my model also accepts the same as yours. My solution is export the lumi as a brand new tensor. 

https://github.com/JSYRD/krccsnet/blob/master/lib/krccsnet_encoder.dart 

In the function `getEncoderInputTensor`.
I'd grateful if it's helpful.

**Comment by PaulTR** [comment]
Also while this is in development, ML Kit might be a solid answer for you (even long term) - https://pub.dev/packages/google_mlkit_image_labeling

**Comment by Alexi-Zemcov** [comment]
> > By the way, I faced into the problem described in this comment. [am15h/tflite_flutter_plugin#133 (comment)](https://github.com/am15h/tflite_flutter_plugin/issues/133#issuecomment-1118419145)
> > My .tflite model accepts the required grayscale image data in **one** channel. But in fact, as the `tfLiteTensorByteSize` method shows, I have **4 times** more data.
> > Does anyone have any ideas what to do with this?
> 
> Nice to meet you again, and my model also accepts the same as yours. My solution is export the lumi as a brand new tensor.
> 
> https://github.com/JSYRD/krccsnet/blob/master/lib/krccsnet_encoder.dart
> 
> In the function `getEncoderInputTensor`. I'd be grateful if it's helpful.

Unfortunately it didn't work for my model. Now it trow StateError even earlier on the `tfLiteInterpreterAllocateTensors` method.
Perhaps I lack a deeper understanding of how C code works to set up my model properly.

**Comment by Alexi-Zemcov** [comment]
> Also while this is in development, ML Kit might be a solid answer for you (even long term) - https://pub.dev/packages/google_mlkit_image_labeling

Thank you very much! So now I will try this package, may be it will be easier way for me.

**Comment by luiscib3r** [comment]
In this PR #49 I added an example of image classification using mobilenet. You can also check it in my fork https://github.com/luiscib3r/flutter-tflite/tree/develop/example/image_classification_mobilenet. Any questions, suggestions, or bug reports are welcome.

**Comment by luiscib3r** [comment]
is done: https://github.com/tensorflow/flutter-tflite/tree/main/example/image_classification_mobilenet

**Comment by Emon526** [comment]
@luiscib3r thank you for the help.i think there is something wrong with my model .can you please provide me some documentation so that i can build my model

**Comment by luiscib3r** [comment]
@Emon526 If you can send me any error messages you are getting while loading the model I might have a better idea. One tip that I follow with all models is to do getTensorInputs and getTensorOutputs and print their value, so I can clearly see the shape of the tensors and the type of data they accept. So then I transform the data I have based on what the model expects to receive.

**Comment by Emon526** [comment]
@luiscib3r i  didn't getting any errors.but i am not getting the expected result.the model is trained by another developer. previously i was working with flutter_tflite package from pub.dev and i got the perfect result but now i cant do it.

**Comment by PaulTR** [comment]
Can you try with version 0.9.1? That should be a direct clone of the original repo and will help narrow down app vs plugin issues.
