### ISSUE TITLE
Empty predictions

### ISSUE THREAD

**Issue by chathurach** [tensorflow/flutter-tflite#100]
I have trained a custom model using yolov5s and converted that model to tflite. I was able to run the model without any errors but no predictions are present in the output. I suspect it may be due to some issue with converting the image to a float32 list input. here are my input and output tensor shapes.
`[1, 640, 640, 3]
[1, 25200, 6]` 
 these are what neutron app display of the model.
`name: serving_default_input_1:0
type: float32[1,640,640,3]
location: 0`
`name: StatefulPartitionedCall:0
type: float32[1,25200,6]
location: 532`

here is my image to List<List<List<double>>> function
```
Future<List<List<List<double>>>> processImage(var imagePath) async {
    final rawImage = await File(imagePath.path).readAsBytes();
    // decode image
    final image = img.decodeImage(rawImage);
    // Resize image to 640x640
    final imageInput = img.copyResize(
      image!,
      width: 640,
      height: 640,
    );
    // Get matrix representation
    final imageMatrix = List.generate(
      imageInput.height,
      (y) => List.generate(
        imageInput.width,
        (x) {
          final pixel = imageInput.getPixel(x, y);
          return [
            (img.getRed(pixel) - 100) / 127.5,
            (img.getGreen(pixel) - 100) / 127.5,
            (img.getBlue(pixel) - 100) / 127.5
          ];
        },
      ),
    );
    return imageMatrix;
  }
```

I'm not sure this is the right way to convert input image data for the model.

```[√] Flutter (Channel stable, 3.10.0, on Microsoft Windows [Version 10.0.22621.1702], locale en-US)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2022 17.1.0)
[!] Android Studio (not installed)
[√] VS Code (version 1.79.2)
[√] Connected device (4 available)
    ! Device emulator-5556 is offline.
[√] Network resources```

**Comment by azazadev** [comment]
if issue is due to image conversion to float32 try something like this : 

```
      ...
      ...
      final decodeImage = img_lib.decodeImage(data);
      final imageInput = img_lib.copyResize(
        decodeImage!,
        width: 640,
        height: 640,
      );
      Uint8List byte8 = imageToByteListFloat32(imageInput, 640, 127.5, 127.5);
      
      // replace with your output --> this is only example
      final output = {
        0: [List<List<num>>.filled(10, List<num>.filled(4, 0))],
        1: [List<num>.filled(10, 0)],
        2: [List<num>.filled(10, 0)],
        3: [0.0],
      };
      _interpreter!.runForMultipleInputs([byte8.buffer], output);
      ...
      ...
```


and to convert to Float32

```
  Uint8List imageToByteListFloat32(img_lib.Image image, int inputSize, double mean, double std) {
    var convertedBytes = Float32List(1 * inputSize * inputSize * 3);
    var buffer = Float32List.view(convertedBytes.buffer);
    int pixelIndex = 0;
    for (var i = 0; i < inputSize; i++) {
      for (var j = 0; j < inputSize; j++) {
        var pixel = image.getPixel(j, i);
        buffer[pixelIndex++] = (pixel.r - mean) / std;
        buffer[pixelIndex++] = (pixel.g - mean) / std;
        buffer[pixelIndex++] = (pixel.b - mean) / std;
      }
    }
    return convertedBytes.buffer.asUint8List();
  }

```

**Comment by chathurach** [comment]
Thank you. It worked. The main issue was that I was using the `interpreter.run(input,output)` instead of `intrepreter.runForMultipleInputs(input, output)`.  Also your image conversion code worked. Thank you.

**Comment by chathurach** [comment]
closed since this was fixed with the above comment.

**Comment by billbch** [comment]
Hi, I'm also running yolov5s, I'm doing a lot of tests to see what the problem is, my model runs "fine", but it doesn't predict anything in the output, I've been testing a lot of things with the output but I think I have problems with the input as well.

Could you help me by saying that you changed in the classifier.dart class?

If your problem was the input suddenly it's also mine.


`Map<String, dynamic>? predict(imageLib.Image image) {
    print("Entramos a predict");
    var predictStartTime = DateTime.now().millisecondsSinceEpoch;
    print("predictStartTime= "+predictStartTime.toString());

    if (_interpreter == null) {
      print("Interpreter not initialized");
      return null;
    }

    var preProcessStart = DateTime.now().millisecondsSinceEpoch;
    print("preProcessStart = "+preProcessStart.toString());

    // Create TensorImage from image
    TensorImage inputImage = TensorImage.fromImage(image);

    print("inputImage = "+inputImage.toString());
    // Pre-process TensorImage
    inputImage = getProcessedImage(inputImage);
    print("inputImage getProcesImage = "+inputImage.toString());

    var preProcessElapsedTime =
        DateTime.now().millisecondsSinceEpoch - preProcessStart;
    print("preProcessElapsedTime = "+preProcessElapsedTime.toString());
    print("_outputShapes = "+_outputShapes![0].toString());
    print("_outputShapes = "+_outputShapes![1].toString());
    print("_outputShapes = "+_outputShapes![2].toString());
    print("_outputShapes = "+_outputShapes![3].toString());
    // TensorBuffers for output tensors
    
   /* TensorBuffer outputLocations = TensorBufferFloat(_outputShapes![0]);
    TensorBuffer outputClasses = TensorBufferFloat(_outputShapes![2]);
    TensorBuffer outputScores = TensorBufferFloat(_outputShapes![1]);
    TensorBuffer numLocations = TensorBufferFloat(_outputShapes![3]);
*/

    TensorBuffer outputLocations = TensorBufferFloat(_outputShapes![1]);
    TensorBuffer outputClasses = TensorBufferFloat(_outputShapes![0]);
    TensorBuffer outputScores = TensorBufferFloat(_outputShapes![3]);
    TensorBuffer numLocations = TensorBufferFloat(_outputShapes![2]);

    print("PASAMOS LOS TENSORESbufer = ");

    // Inputs object for runForMultipleInputs
    // Use [TensorImage.buffer] or [TensorBuffer.buffer] to pass by reference
    List<Object> inputs = [inputImage.buffer];

    print("inputs = "+inputs.toString());
    // Outputs map
    Map<int, Object> outputs = {
      0: outputLocations.buffer,
      1: outputClasses.buffer,
      2: outputScores.buffer,
      3: numLocations.buffer,
    };
    print("outputs = "+outputs.toString());

    var inferenceTimeStart = DateTime.now().millisecondsSinceEpoch;

    print("inferenceTimeStart = "+inferenceTimeStart.toString());
    // run inference
    print("inputs shape= "+inputs[0].toString());
    print("outputs = "+outputs.toString());

    print('=====================inputTensors=====================');
    for (var input in _interpreter!.getInputTensors()) {
      print('$input');
    }
    print('=====================outputTensors=====================');
    for (var output in _interpreter!.getOutputTensors()) {
      print('$output');
    }
    try {
      _interpreter?.runForMultipleInputs(inputs, outputs);
    } catch(e){
      print("Error $e");
    }`

**Comment by chathurach** [comment]
@billbch, I think you are using the package **tflite_flutter_helper** which is depreciated. Insted use [tflite_flutter_helper_plus](https://pub.dev/packages/tflite_flutter_helper_plus)  or manually do the image normalization like I did above before running the intrepreter.

**Comment by billbch** [comment]
> @billbch, I think you are using the package **tflite_flutter_helper** which is depreciated. Insted use [tflite_flutter_helper_plus](https://pub.dev/packages/tflite_flutter_helper_plus) or manually do the image normalization like I did above before running the intrepreter.

Yes, I have already added a function to convert from uint8 to float32, thanks.
Now I have a new error yuju!

I/flutter (29104): Error RangeError (index): Index out of range: index should be less than 40: 40

**Comment by billbch** [comment]
I managed to solve the error, now I have a new one yujuu!! hahaha I/flutter (29104): Error RangeError (index): Index out of range: index should be less than 40: 40 At least this gives me a number in the error. Enviado desde Correo para Windows De: Chathura ChamikaraEnviado: Thursday, September 7, 2023 1:35 AMPara: tensorflow/flutter-tfliteCC: billbch; MentionAsunto: Re: [tensorflow/flutter-tflite] Empty predictions (Issue ***@***.***, I think you are using the package tflite_flutter_helper which is depreciated. Insted use tflite_flutter_helper_plus or manually do the image normalization like I did above before running the intrepreter.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
