### ISSUE TITLE
how can i make this work on android 4.4.4 

### ISSUE THREAD

**Issue by lekthedeveloper** [tensorflow/flutter-tflite#102]
i am getting this error message below

Restarted application in 5,161ms.
D/Activity( 7207): #1 setTransGradationModeColor false
D/ViewRootImpl( 7207): ViewPostImeInputStage ACTION_DOWN
E/flutter ( 7207): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libtensorflowlite_jni.so': dlopen failed: cannot locate symbol "__register_atfork" referenced by "libtensorflowlite_jni.so"...
E/flutter ( 7207): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter ( 7207): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter ( 7207): #2      _dylib.<anonymous closure>
E/flutter ( 7207): #3      _dylib
E/flutter ( 7207): #4      _dylib (package:tflite_flutter/src/bindings/bindings.dart)
E/flutter ( 7207): #5      tfliteBinding
E/flutter ( 7207): #6      tfliteBinding (package:tflite_flutter/src/bindings/bindings.dart)
E/flutter ( 7207): #7      new Model.fromBuffer
E/flutter ( 7207): #8      new Interpreter.fromBuffer
E/flutter ( 7207): #9      Interpreter.fromAsset
E/flutter ( 7207): <asynchronous suspension>
E/flutter ( 7207): #10     _FaceComparisonPageState._loadModel
E/flutter ( 7207): <asynchronous suspension>
E/flutter ( 7207):

**Comment by PaulTR** [comment]
Oh boy, no I _really_ doubt it :) Min SDK for Android that we support in samples is 21 (Lollipop), which was initially released in October of 2014 (coming up on 9 years ago :)). Anything before that (though even Lollipop at this point) is pure luck if it works. Sorry about that!
