### ISSUE TITLE
[Request] Support Dart (server side without flutter)

### ISSUE THREAD

**Issue by gwcangtip** [tensorflow/flutter-tflite#104]
First, thank you for developing this library, but the dart language can run on the server side (exe binary), Please make the library support server side because I want to add your library to the http server, thank you very much, sorry to bother you

**Comment by PaulTR** [comment]
Hey @gwcangtip. I don't think that really fits within the scope of this library :) It's pretty directly for edge ML. This is definitely something I would post to the [TensorFlow issues tracker](https://github.com/tensorflow/tensorflow/issues) though!
