### ISSUE TITLE
same prediction for any input image

### ISSUE THREAD

**Issue by azazadev** [tensorflow/flutter-tflite#106]
I'm running this model 

```
flutter: [Tensor{_tensor: Pointer: address=0x14155c000, name: inputs_0, type: float32, shape: [1, 416, 416, 3], data: 2076672}]
flutter: [Tensor{_tensor: Pointer: address=0x14157a530, name: Identity, type: float32, shape: [16, 7], data: 448}]
```

in python prediction working fine and I have the correct score with correct label for given image

```
    def predict(self, image_path):
        image = cv2.imread(image_path)
        resized_image = cv2.resize(
            image,
            (416, 416)
        )
        image = np.ascontiguousarray(resized_image, dtype=np.float32)
        test_image = np.expand_dims(image, axis=0)
        input_tensor_index = self.input_details[0]['index']
        self.interpreter.set_tensor(input_tensor_index, test_image)
        self.interpreter.invoke()
        tflite_model_predictions = self.interpreter.get_tensor(self.output_details[0]['index'])
        class_ids, scores, bboxes = tflite_model_predictions[..., 1:2], tflite_model_predictions[..., 2:3], tflite_model_predictions[..., 3:]
        score = max(scores)
        label = np.argmax(scores)
        print(score) // the max score
        print(index)   // corresponding label
```

```
score --> [0.92109966] --> label 1
score --> [0.9576158]  --> label 2
...
...

```

now when I'm trying to run the same model on flutter I got wrong score and everytime the same label for any input image

 ```
 Uint8List analyseImage(Uint8List imageData) {
    final image = img.decodeImage(imageData.buffer.asUint8List())!;
    final imageInput = img.copyResize(image, width: 416, height: 416);
    Uint8List byte = imageToByteListFloat32(imageInput, 416, 127.5, 127.5);
    final output = {0: List<List<num>>.filled(16, List<num>.filled(7, 0))};
    _interpreter!.runForMultipleInputs([byte], output);
    final elements = output.values.toList().elementAt(0);
    List<num> allValue = [];
    for (var element in elements) {
      allValue.add(element.elementAt(2));
    }
    num max = allValue.reduce((value, element) => value > element ? value : element);
    int maxIndex = allValue.indexOf(max);
    print('$max ---> $maxIndex');
    return imageData;
  }
```

```
flutter: 0.0007955206674523652 ---> 7 // this should be 0.92109966 and label 1 not 7
flutter: 0.0008014166378416121 ---> 7 // this should be 0.9576158 and label 2 not 7
flutter: 0.0007995906635187566 ---> 7
flutter: 0.0008015930652618408 ---> 7
```

probably something wrong in image preprocessing ? any idea please ?

**Comment by PaulTR** [comment]
Please share a link to your model.

**Comment by azazadev** [comment]
> Please share a link to your model.

will provide git in next 20 mn

**Comment by azazadev** [comment]
git [sample](https://github.com/azazadev/flutter-tflite-fazaza/blob/v2/example/object_detection_ssd_mobilenet/lib/main.dart), run main and click on 01, 02 or 03 all should return correct score/label in console, but wrong value is returned

**Comment by azazadev** [comment]
> git [sample](https://github.com/azazadev/flutter-tflite-fazaza/blob/v2/example/object_detection_ssd_mobilenet/lib/main.dart), run main and click on 01, 02 or 03 all should return correct score/label in console, but wrong value is returned

add missing models in git

**Comment by xyzacademic** [comment]
What's your dart version? If you upgraded it to dart 3.+, try reversing it to <=2.19 if it works.

**Comment by azazadev** [comment]
Hi @xyzacademic : this is what I did

_**current version**_

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.5, on macOS 13.1 22C65 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
[✓] VS Code (version 1.79.2)
[✓] Connected device (2 available)
[✓] Network resources

_**downgrade to 2.19.6**_

git checkout 3.7.12

dart --version
Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_arm64"


**_update  pubspec.yaml_**
change sdk: ">=3.0.0 <4.0.0" to  sdk: ">=2.17.0-0 <3.0.0" 

**_full cleanup_**

flutter clean
rm -rf ios/Podfile.lock ios/Pods ios/Flutter/Flutter.podspec ios/pubspec.lock ios/Runner.xcworkspace/
rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData
cd ios
rm -rf Podfile.lock
pod deintegrate
flutter pub get
arch -x86_64 pod install --repo-update


**_run again and same issue, output is the same for any image_** 


flutter: 0.0007939497008919716 ---> label  7
flutter: 0.0007998716901056468 ---> label 7
flutter: 0.0007980188820511103 ---> label 7

please let me know if I'm doing something wrong here

**Comment by xyzacademic** [comment]
> Hi @xyzacademic : this is what I did
> 
> _**current version**_
> 
> flutter doctor Doctor summary (to see all details, run flutter doctor -v): [✓] Flutter (Channel stable, 3.10.5, on macOS 13.1 22C65 darwin-arm64, locale en-FR) [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3) [✓] Xcode - develop for iOS and macOS (Xcode 14.2) [✓] Chrome - develop for the web [✓] Android Studio (version 4.0) [✓] Android Studio (version 2021.1) [✓] IntelliJ IDEA Community Edition (version 2022.3.1) [✓] VS Code (version 1.79.2) [✓] Connected device (2 available) [✓] Network resources
> 
> _**downgrade to 2.19.6**_
> 
> git checkout 3.7.12
> 
> dart --version Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_arm64"
> 
> **_update pubspec.yaml_** change sdk: ">=3.0.0 <4.0.0" to sdk: ">=2.17.0-0 <3.0.0"
> 
> **_full cleanup_**
> 
> flutter clean rm -rf ios/Podfile.lock ios/Pods ios/Flutter/Flutter.podspec ios/pubspec.lock ios/Runner.xcworkspace/ rm -rf ~/Library/Caches/CocoaPods Pods ~/Library/Developer/Xcode/DerivedData cd ios rm -rf Podfile.lock pod deintegrate flutter pub get arch -x86_64 pod install --repo-update
> 
> **_run again and same issue, output is the same for any image_**
> 
> flutter: 0.0007939497008919716 ---> label 7 flutter: 0.0007998716901056468 ---> label 7 flutter: 0.0007980188820511103 ---> label 7
> 
> why you think downgrade can help ?
> 
> please let me know if I'm doing something wrong here
> 
> I suspect something wrong here but I don't know what is exactly
> 
> ```
> final image = img.decodeImage(imageData.buffer.asUint8List())!;
> final imageInput = img.copyResize(image, width: 416, height: 416);
> Uint8List byte = imageToByteListFloat32(imageInput, 416, 127.5, 127.5);
> final output = {0: List<List<num>>.filled(16, List<num>.filled(7, 0))};
> _interpreter!.runForMultipleInputs([byte], output);
> ```

Looks correct. 

By the way, did you check the image if it looks correct before sending it into tflite model. You could save the pixel list into a JSON, and load it in python to visualize it. If everything is ok, then I can do nothing probably.

**Comment by azazadev** [comment]
genius idea @xyzacademic !!
I export image as json in flutter, and import / process image in my python code and I'm able to reproduce the same pattern, output of my python code is something like this now

Connected to pydev debugger (build 221.5080.212)
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

score --> [0.001887] --> label 7
score --> [0.001887] --> label 7


this means issue in image preprocessing in my flutter code, but I'm not able to figure out ? can you please import the [git example](https://github.com/azazadev/flutter-tflite-fazaza/blob/b14e7b38f6ef5262dc71d2bf1c0a8e0e1c54a259/example/object_detection_ssd_mobilenet/lib/object_detection.dart#L49) and try ?

**Comment by azazadev** [comment]
quick update, now I did the reverse, export image from python as json and import in flutter, it's working fine and I got correct score/label !!!

```
  String jsonStr = await rootBundle.loadString('assets/models/image_matrix.json');
  final jsonData = json.decode(jsonStr);
  final List<dynamic> pixels = jsonData['pixels'];
  Uint8List byteList = Uint8List.fromList(pixels.cast<int>());
  final image2 = img.Image.fromBytes(width: 416, height: 416, bytes: byteList.buffer);
  final imageMatrix = List.generate(
    image2.height,
    (y) => List.generate(
      image2.width,
      (x) {
        final pixel = image2.getPixel(x, y);
        return [pixel.r, pixel.g, pixel.b];
      },
    ),
  );
  final output = List<List<double>>.filled(16, List<double>.filled(7, 0));
  _interpreter!.run([imageMatrix], output);
  final elements = output.toList();
```

output

**flutter: 0.9210997223854065 ---> 0**


this mean something wrong which this flutter code when I process image

```
final image = img.decodeImage(imageData.buffer.asUint8List())!;
final imageInput = img.copyResize(image, width: 416, height: 416);
Uint8List byte = imageToByteListFloat32(imageInput, 416, 127.5, 127.5);
final output = {0: List<List<num>>.filled(16, List<num>.filled(7, 0))};
_interpreter!.runForMultipleInputs([byte], output);
```

**Comment by xyzacademic** [comment]
> quick update, now I did the reverse, export image from python as json and import in flutter, it's working fine and I got correct score/label !!!
> 
> ```
>   String jsonStr = await rootBundle.loadString('assets/models/image_matrix.json');
>   final jsonData = json.decode(jsonStr);
>   final List<dynamic> pixels = jsonData['pixels'];
>   Uint8List byteList = Uint8List.fromList(pixels.cast<int>());
>   final image2 = img.Image.fromBytes(width: 416, height: 416, bytes: byteList.buffer);
>   final imageMatrix = List.generate(
>     image2.height,
>     (y) => List.generate(
>       image2.width,
>       (x) {
>         final pixel = image2.getPixel(x, y);
>         return [pixel.r, pixel.g, pixel.b];
>       },
>     ),
>   );
>   final output = List<List<double>>.filled(16, List<double>.filled(7, 0));
>   _interpreter!.run([imageMatrix], output);
>   final elements = output.toList();
> ```
> 
> output
> 
> **flutter: 0.9210997223854065 ---> 0**
> 
> this mean something wrong which this flutter code when I process image
> 
> ```
> final image = img.decodeImage(imageData.buffer.asUint8List())!;
> final imageInput = img.copyResize(image, width: 416, height: 416);
> Uint8List byte = imageToByteListFloat32(imageInput, 416, 127.5, 127.5);
> final output = {0: List<List<num>>.filled(16, List<num>.filled(7, 0))};
> _interpreter!.runForMultipleInputs([byte], output);
> ```

I quickly looked at your function
```dart
  Uint8List imageToByteListFloat32(img.Image image, int inputSize, double mean, double std) {
    var convertedBytes = Float32List(1 * inputSize * inputSize * 3);
    var buffer = Float32List.view(convertedBytes.buffer);
    int pixelIndex = 0;
    for (var i = 0; i < inputSize; i++) {
      for (var j = 0; j < inputSize; j++) {
        var pixel = image.getPixel(j, i);
        buffer[pixelIndex++] = (pixel.r - mean) / std;
        buffer[pixelIndex++] = (pixel.g - mean) / std;
        buffer[pixelIndex++] = (pixel.b - mean) / std;
      }
    }
    return convertedBytes.buffer.asUint8List();
  }
}
``` 
The final return is a uint8 rather than a float32. everything will become 1 or 2, right?

**Comment by azazadev** [comment]
@xyzacademic I take this fonction from [here](https://github.com/shaqian/flutter_tflite/blob/ce8075a391e02e0cc0bc6c2db950aa961a17d745/example/lib/main.dart#L145C4-L145C4) and I expect that this will convert to Float32, now I update my processing image function to have the same pattern like what I use to process python Image, so imageToByteListFloat32 will not be used, new function : 

```
    final image = img.decodeJpg(imageData);
    final imageInput = img.copyResize(image!, width: 416, height: 416);
    final imageMatrix = List.generate(
      imageInput.height,
      (y) => List.generate(
        imageInput.width,
        (x) {
          final pixel = imageInput.getPixel(x, y);
          return [pixel.r, pixel.g, pixel.b];
        },
      ),
    );
    final output = List<List<num>>.filled(16, List<num>.filled(7, 0));
    _interpreter!.run([imageMatrix], output);
```

new with this new code we return another wrong prediction value with overtime 10 as label  not 7 like what we have before !!!

flutter: 0.0017262777546420693 ---> 10
flutter: 0.0017262777546420693 ---> 10


I'm pretty sure that there is one line to change to make it work but I don't know how as I'm beginning

**Comment by xyzacademic** [comment]
@azazadev You take out the pre-processing function but forget to normalize the data. 

```dart
return [pixel.r, pixel.g, pixel.b];
```

change to 
```dart
return [(pixel.r - mean) / std, (pixel.g - mean) / std, (pixel.b - mean) / std];
```

**Comment by azazadev** [comment]
> @azazadev You take out the pre-processing function but forget to normalize the data.
> 
> ```dart
> return [pixel.r, pixel.g, pixel.b];
> ```
> 
> change to
> 
> ```dart
> return [(pixel.r - mean) / std, (pixel.g - mean) / std, (pixel.b - mean) / std];
> ```

@xyzacademic Thanks for your help !

this code return 10 eveytime
```

final imageMatrix = List.generate(
imageInput.height,
(y) => List.generate(
  imageInput.width,
  (x) {
    final pixel = imageInput.getPixel(x, y);
    return [pixel.r, pixel.g, pixel.b];
  },
),
);
flutter: 0.0005880682147108018 ---> 10
flutter: 0.0017262777546420693 ---> 10
```

and this one return 7 everytime

```
    final imageMatrix = List.generate(
      imageInput.height,
      (y) => List.generate(
        imageInput.width,
        (x) {
          final pixel = imageInput.getPixel(x, y);
          return [(pixel.r - 127.5) / 127.5, (pixel.g - 127.5) / 127.5, (pixel.b - 127.5) / 127.5];
        },
      ),
    );
flutter: 0.0007998716901056468 ---> 7
flutter: 0.0007980188820511103 ---> 7
```

how I can  normalize the data to make it work correctly ?

**Comment by xyzacademic** [comment]
@azazadev 

Did you visualize the imageMatrix(before - 127.5 / 127.5) in python? 

Is it looks the same as the image you give? 

You can use `matplotlib.pyplot` to visualize it. 
```python
plt.imshow(imageMatrix)
plt.plot()
```
 imageMatrix should be a [416, 416, 3] array.

**Comment by azazadev** [comment]
> 

I have try this in python code but I'm not able to understand what this mean and how to use

```
      image = np.ascontiguousarray(resized_image, dtype=np.float32)
      test_image = np.expand_dims(image, axis=0)
      input_tensor_index = self.input_details[0]['index']
      plt.imshow(image)
      plt.plot()
```


![Screenshot2023_07_11_191202](https://github.com/tensorflow/flutter-tflite/assets/68111176/97429262-0683-4f64-9633-bdeb8085c98f)

**Comment by azazadev** [comment]
@xyzacademic  if you have time you can import the [git sample ](https://github.com/azazadev/flutter-tflite-fazaza/tree/v2/example/object_detection_ssd_mobilenet/lib)and you will reproduce in few minute

**Comment by azazadev** [comment]
@PaulTR @xyzacademic please have a look, this will take few minutes for you to reproduce and figure out what is missing in image preprocessing

**Comment by xyzacademic** [comment]
> @PaulTR @xyzacademic please have a look, this will take few minutes for you to reproduce and figure out what is missing in image preprocessing

I tried, but didn't figure it out.

**Comment by azazadev** [comment]
> > @PaulTR @xyzacademic please have a look, this will take few minutes for you to reproduce and figure out what is missing in image preprocessing
> 
> I tried, but didn't figure it out.

Thanks @xyzacademic for your time !!!

@PaulTR need your lights please !

**Comment by PaulTR** [comment]
I don't think it'll only take me a few minutes :P I have it in my backlog though in case no one else is able to figure it out any time soon, but I'll have to time box it unfortunately.

**Comment by azazadev** [comment]
> 

Hi @PaulTR I hope this is not so far in your backlog :)

**Comment by PaulTR** [comment]
Hey @azazadev, yeah I'm honestly not too sure when I'll be able to get to this with other work (I've been trying to find others to also work on this project, but so far it's a no go :)). Might be out of luck hunting the details of it from my side.

**Comment by azazadev** [comment]
> Hey @azazadev, yeah I'm honestly not too sure when I'll be able to get to this with other work (I've been trying to find others to also work on this project, but so far it's a no go :)). Might be out of luck hunting the details of it from my side.

Thanks @PaulTR , I can understand
