### ISSUE TITLE
Model Theft - Security

### ISSUE THREAD

**Issue by alexw92** [tensorflow/flutter-tflite#115]
From what I have read there is currently nothing build-in to prevent or AT LEAST make it more difficult to just steal the model.

Since quantizied TFlite models are already hard to train since weaker mobile phones require smaller models (and thus training with even bigger datasets to make them accurately enough) and people invest lots of time in development of models one should not be able to just copy the tflite file from the assets.

I know Google states on its page that model theft is "typically" not a big problem because the model alone without the other features and usage of the app make it less valuable but just think of a competitor which just lacks a compute vision feature another company has provided in its app via Flutter-Tflite. 

Why not adding a way to load an encrypted model and providing it the private key just-in-time? That would be a great start.
When Flutter-Tflite one day will provide more security features to make it more tricky to just steal expensively trained models TF-Lite Adoption in Flutter would become a really cool thing!

Is anything like that planned? I cannot imagine I am the only one thinking about this.

**Comment by Megatronicus** [comment]
> From what I have read there is currently nothing build-in to prevent or AT LEAST make it more difficult to just steal the model.
> 
> Since quantizied TFlite models are already hard to train since weaker mobile phones require smaller models (and thus training with even bigger datasets to make them accurately enough) and people invest lots of time in development of models one should not be able to just copy the tflite file from the assets.
> 
> I know Google states on its page that model theft is "typically" not a big problem because the model alone without the other features and usage of the app make it less valuable but just think of a competitor which just lacks a compute vision feature another company has provided in its app via Flutter-Tflite.
> 
> Why not adding a way to load an encrypted model and providing it the private key just-in-time? That would be a great start. When Flutter-Tflite one day will provide more security features to make it more tricky to just steal expensively trained models TF-Lite Adoption in Flutter would become a really cool thing!
> 
> Is anything like that planned? I cannot imagine I am the only one thinking about this.

How did you make that model, did you take all those pictures, made all those images? Did you pay all those photographers or did you just get everything for free to make the model. My friend, this is a function that should be available to everyone and provided for free just like those images you got on the web. There are thousands of models out there for free anyway.

**Comment by alexw92** [comment]
@PaulTR Thanks for replying. I understand. If I find time this year I will build this and contribute!

@Megatronicus I am not sure if I got you correctly. Yes I am taking pictures myself and also paying others to create a dataset and dont wish competitors of mine to get that for free. Yes there are thousands of free models (trained on public datasets) sure but way more are not public because creating annotations and training to realize a custom use-case can cost a fortune.

**Comment by Megatronicus** [comment]
In that case I understand. Simple solution, put a watermark of your company logo in the layer above the image or video while it's scanning. That way even if someone does take it, it will still advertise your company.

**Comment by alexw92** [comment]
@Megatronicus Yes thats an idea and I will do this of course. Still creating a fail prove watermark is incredibly difficult. I would like to use multiple security layers like Watermark plus Model Encryption plus Obfuscation. 100% Security is never guaranteed though. :)

**Comment by PaulTR** [comment]
Closing this issue out since it's more of a higher level TensorFlow issue than one specific to this plugin. Will keep an eye out for the PR though! I also sent the request up to eng.
