### ISSUE TITLE
Changelog not updating on pub.dev

### ISSUE THREAD

**Issue by sarthakydv** [tensorflow/flutter-tflite#12]
The change log on pub.dev is stuck at 0.9.0 while the current package version is 0.9.4

Please add release notes.

<img width="820" alt="image" src="https://user-images.githubusercontent.com/41507081/235306077-95aa57e2-589f-4365-b331-56932b449d03.png">

**Comment by PaulTR** [comment]
Convention on change notes has only been on minor releases, not patch. Difference between 0.9.0 and 0.9.4 is all README and ownership updates. Change logs will be updated when there's actually a published change to mention :)
