### ISSUE TITLE
_TypeError (type 'List<double>' is not a subtype of type 'List<int>' of 'value') 

### ISSUE THREAD

**Issue by izzyvenici** [tensorflow/flutter-tflite#128]
i am new to this 
i knew the problem was my model using float32 as the final output 
how i convert my model output to unit8
![image](https://github.com/tensorflow/flutter-tflite/assets/53007261/7b7818d0-9424-4a17-a607-61f40736d32e)
![image](https://github.com/tensorflow/flutter-tflite/assets/53007261/e6d25d9d-bcb2-4bfe-b5a8-39e7b17342a1)

**Comment by Anthrapper** [comment]
change ur code to 
`final output = [ List<int>.filled(isolateModel.outputShape[1],0.0)];`
 that is `0.0` instead of ` 0`

**Comment by izzyvenici** [comment]
thank you it works ahahaha
