### ISSUE TITLE
Tf delegate options guide!

### ISSUE THREAD

**Issue by eav-solution** [tensorflow/flutter-tflite#158]
Hello sir,

I have a question about Delegate Options.
Currently, I cannot find guide about it.
So that, how to enable
XNNPACK, GPU, NNAPI, Apple Metal.
Should I need re-build tflite to support it ?

**Comment by PaulTR** [comment]
So in the example apps we do this and I'm guessing it's more of what you're looking for:

```
    // Use XNNPACK Delegate
    if (Platform.isAndroid) {
      options.addDelegate(XNNPackDelegate());
    }

    // Use Metal Delegate
    if (Platform.isIOS) {
      options.addDelegate(GpuDelegate());
    }
```

**Comment by andynewman10** [comment]
@PaulTR there are situations where the XNNPack delegate doesn't work with your plugin, however it works when using the native TF Lite Android runtime. See https://github.com/tensorflow/flutter-tflite/issues/159
