### ISSUE TITLE
[Android] Why did the minSdk get raised compared to the old plugin

### ISSUE THREAD

**Issue by CaptainDario** [tensorflow/flutter-tflite#174]
As desktop support landed, I wanted to switch from the old tf lite plugin to this one.
While doing this I noticed that this plugin now requires a minSdkVersion of 26 and before it was [16](https://github.com/am15h/tflite_flutter_plugin/blob/687ad63199da9196ab759ab17809221c944a5270/android/build.gradle#L28).
Is there a reason for this or is it possible to lower this requirement again to 16?

**Comment by st-duymai** [comment]
Hi. This update is related to issue #73

**Comment by CaptainDario** [comment]
Thank you and sorry that I missed that issue.
I think fixing this problem is quite crucial as I have quite some users with an Android version < 8.

Closing this as it is basically a duplicate.
