### ISSUE TITLE
Invalid argument(s): Failed to load dynamic library 'libtensorflowlite_c.so': dlopen failed: library "libtensorflowlite_c.so" not found on Android 13

### ISSUE THREAD

**Issue by Istiak-Ahmed78** [tensorflow/flutter-tflite#182]
I'm encountering the error on executing the following line on my physical device of Android version 13:
```dart
 Interpreter interpreter = await Interpreter.fromAsset('model.tflite');
````
Here is the error:
```console
flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Failed to load dynamic library 'libtensorflowlite_c.so': dlopen failed: library "libtensorflowlite_c.so" not found
E/flutter (14085): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
E/flutter (14085): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
E/flutter (14085): #2      tflitelib.<anonymous closure> (package:tflite_flutter/src/bindings/dlib.dart:34:27)
E/flutter (14085): #3      tflitelib (package:tflite_flutter/src/bindings/dlib.dart:42:2)
E/flutter (14085): #4      tflitelib (package:tflite_flutter/src/bindings/dlib.dart)
E/flutter (14085): #5      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart:10:35)
E/flutter (14085): #6      tfLiteModelCreateFromBuffer (package:tflite_flutter/src/bindings/model.dart)
E/flutter (14085): #7      new Model.fromBuffer (package:tflite_flutter/src/model.dart:36:19)
E/flutter (14085): #8      new Interpreter.fromBuffer (package:tflite_flutter/src/interpreter.dart:93:25)
E/flutter (14085): #9      Interpreter.fromAsset (package:tflite_flutter/src/interpreter.dart:112:24)
E/flutter (14085): <asynchronous suspension>
E/flutter (14085): #10     _ScannerScreenState.predict (package:ml_app/scanner_screen.dart:36:31)
E/flutter (14085): <asynchronous suspension>
E/flutter (14085): #11     _ScannerScreenState.build.<anonymous closure> (package:ml_app/scanner_screen.dart:73:31)
E/flutter (14085): <asynchronous suspension>
```
How to solve this? Is this issue from my model? Help me please.

**Comment by Istiak-Ahmed78** [comment]
[This instruction](https://stackoverflow.com/questions/69554879/failed-to-load-dynamic-library-libtensorflowlite-c-so-dlopen-failed-library) solved my issue.

**Comment by manofgodjr** [comment]
I/flutter ( 3385): Can't initialize Classifier: Invalid argument(s): Failed to load dynamic library 'libtensorflowlite_c.so': dlopen failed: library "libtensorflowlite_c.so" not found
I/flutter ( 3385): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
I/flutter ( 3385): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
I/flutter ( 3385): #2      tflitelib.<anonymous closure> (package:tflite_flutter_plus/src/bindings/dlib.dart:33:27)


got this issue tried using install.bat still didnt download

**Comment by sruizhuenei** [comment]
Hello...I'm trying YoloV8 model into a flutter vision example but I have this error:

`I/flutter (23204): Start loading the model...
D/nativeloader(23204): Load /data/app/~~oudJE8mHc0sHDowCMMjoCQ==/com.example.yolo_test-HsLq1Powc2PCdyOMkTqNTg==/base.apk!/lib/arm64-v8a/libtensorflowlite_gpu_jni.so using ns clns-4 from class loader (caller=/data/app/~~oudJE8mHc0sHDowCMMjoCQ==/com.example.yolo_test-HsLq1Powc2PCdyOMkTqNTg==/base.apk): ok
E/libEGL  (23204): call to OpenGL ES API with no current context (logged once per thread)
D/nativeloader(23204): Load /data/app/~~oudJE8mHc0sHDowCMMjoCQ==/com.example.yolo_test-HsLq1Powc2PCdyOMkTqNTg==/base.apk!/lib/arm64-v8a/libtensorflowlite_jni.so using ns clns-4 from class loader (caller=/data/app/~~oudJE8mHc0sHDowCMMjoCQ==/com.example.yolo_test-HsLq1Powc2PCdyOMkTqNTg==/base.apk): ok
I/InterpreterApi(23204): Loaded native library: tensorflowlite_jni
D/nativeloader(23204): Load libtensorflowlite_jni_gms_client.so using ns clns-4 from class loader (caller=/data/app/~~oudJE8mHc0sHDowCMMjoCQ==/com.example.yolo_test-HsLq1Powc2PCdyOMkTqNTg==/base.apk): dlopen failed: library "libtensorflowlite_jni_gms_client.so" not found
I/InterpreterApi(23204): Didn't load native library: tensorflowlite_jni_gms_client`

I have the install.sh scriptexecuted and this files was installed:
![image](https://github.com/user-attachments/assets/f89d312c-be77-44fe-8844-d3b636368fc1)

I don't know why the app search for this file libtensorflowlite_jni_gms_client.so?

Could someone help me with this, please.
Regards!
