### ISSUE TITLE
Unable to find example models

### ISSUE THREAD

**Issue by kaneki666** [tensorflow/flutter-tflite#189]
There is no model in assets model folder for example live_object_detection_ssd_mobilenet and object_detection_ssd_mobilenet

**Comment by PaulTR** [comment]
There's a scripts folder that has the file to run to download the models.

**Comment by kaneki666** [comment]
Thank you very much

**Comment by kaneki666** [comment]
@PaulTR after opening the script is closing quickly. i can't see what's happening! Where it will be download or how i can i see logs!
