### ISSUE TITLE
Has anyone achieved using yolov8 with this package?

### ISSUE THREAD

**Issue by DevNim98** [tensorflow/flutter-tflite#191]
I have succesfully implemented yolov5 with this package, however i can't make it work with yolov8.
I don't have problems running the inference, but the results I obtain do not make sense, I always get way to many detections that forms a diagonal in the image. And what it's crazier is that if I use a black image as input, I get detections.
Im going crazy with this implementation. There is the code, I can't see what im doing wrong.

```
    final labels = (await rootBundle.loadString('assets/ai/labels.txt')).split('\n');
    final interpreter = await Interpreter.fromAsset('assets/ai/yolov8n.tflite');
    final imageData = await rootBundle.load('assets/ai/image.jpg');
    final capturedImage = img.decodeImage(imageData.buffer.asUint8List());

    const inputSize = 640;

    final resizedImage = img.copyResize(
      capturedImage!,
      width: inputSize,
      height: inputSize,
      // maintainAspect: true,
      // backgroundColor: img.ColorRgb8(0, 0, 0),
    );

    final imageMatrix = List.generate(
      inputSize,
      (y) => List.generate(
        inputSize,
        (x) {
          final pixel = resizedImage.getPixel(x, y);
          return [pixel.rNormalized, pixel.gNormalized, pixel.bNormalized];
        },
      ),
    );

    final output = List<num>.filled(1 * 84 * 8400, 0).reshape([1, 84, 8400]);

    interpreter.run([imageMatrix], output);

    final results = output.flatten();
    const offset = 4;
    for (var i = 0; i < results.length; i += (offset + labels.length)) {
      var maxClassConfidence = -1.0;
      var maxClassIndex = -1;
      for (var j = i + offset; j < i + offset + labels.length; j++) {
        if (results[j] > maxClassConfidence) {
          maxClassConfidence = results[j];
          maxClassIndex = j - (i + offset);
        }
      }

      final score = maxClassConfidence;
      if (score < 0.4) continue;

      final label = labels[maxClassIndex];

      var x = results[i] * inputSize;
      var y = results[i + 1] * inputSize;
      var w = results[i + 2] * inputSize;
      var h = results[i + 3] * inputSize;

      final resizedRect =
          Rect.fromCenter(center: Offset(x, y), width: w, height: h);
    }
```

**Comment by DevNim98** [comment]
Nvm, yolov5 output matrix was, [1, 25500, labels + 5], and yolov8 is [1, labels + 4, 8400].
Detections are in last position and not second.

**Comment by loveoverflowdev** [comment]
Oh I saw, I did it.

Could you tell me how I can find the description about the meaning of output shape, such as
yolov5 output matrix was, [1, 25500, labels + 5], and yolov8 is [1, labels + 4, 8400] ?

Thank you very much !

**Comment by WisyNim** [comment]
> Oh I saw, I did it.
> 
> Could you tell me how I can find the description about the meaning of output shape, such as yolov5 output matrix was, [1, 25500, labels + 5], and yolov8 is [1, labels + 4, 8400] ?
> 
> Thank you very much !

@loveoverflowdev I did not find it, I inferred it, however this thread can help you to understand it better https://github.com/ultralytics/ultralytics/issues/7231, the creator himself replied with the explanation.

Hope it helps, and sorry with the late reply.
