### ISSUE TITLE
Model missing in live object detection

### ISSUE THREAD

**Issue by md-rifatkhan** [tensorflow/flutter-tflite#213]
Model missing in live object detection

**Comment by tustoz** [comment]
I assume that the model you are referring to comes from [this example](https://github.com/tensorflow/flutter-tflite/tree/main/example/live_object_detection_ssd_mobilenet/). if so, you need to add your own tflite ssd mobile net model [here](https://github.com/tensorflow/flutter-tflite/tree/main/example/live_object_detection_ssd_mobilenet/assets/models/), just for your information this library currently support for ssd mobile net v1 model. you need to adjust library yourself if you want to use ssd mobile net v2.

**Comment by tustoz** [comment]
@md-rifatkhan

**Comment by md-rifatkhan** [comment]
Got it,, thanks > I assume that the model you are referring to comes from [this example](https://github.com/tensorflow/flutter-tflite/tree/main/example/live_object_detection_ssd_mobilenet/). if so, you need to add your own tflite ssd mobile net model [here](https://github.com/tensorflow/flutter-tflite/tree/main/example/live_object_detection_ssd_mobilenet/assets/models/), just for your information this library currently support for ssd mobile net v1 model. you need to adjust library code by yourself if you want to use ssd mobile net v2.

**Comment by md-rifatkhan** [comment]
Got it, thanks
