### ISSUE TITLE
Why does this package not use dart:ffi instead of MethodChannel ? 

### ISSUE THREAD

**Issue by loveoverflowdev** [tensorflow/flutter-tflite#225]
No Platform Dependency: FFI can be used on any platform where Dart runs, making it a more flexible choice for calling native code directly from Dart without relying on platform-specific code.

Lower Overhead: direct access to native code with minimal overhead compared to MethodChannel

Faster Calls: faster as they are direct function invocations without the need for platform channel serialization and deserialization.

**Comment by PaulTR** [comment]
It was written/started ~5 years ago, then sat idle for a few years, while I think FFI came out 4 years ago if I remember correctly.

**Comment by loveoverflowdev** [comment]
Interesting ! 
Thank for your answer

**Comment by loveoverflowdev** [comment]
> It was written/started ~5 years ago, then sat idle for a few years, while I think FFI came out 4 years ago if I remember correctly.

But as I realized, using FFI instead of method channel for mobile platforms would be not good idea.

Because FFI requires platform-specific dynamic linking files (like .so or .dll) to interact with native code, managing these files for various mobile device architectures (ARM, x86, etc.) can be cumbersome.

Unlike MethodChannel, FFI might necessitate rebuilding apps for different chipset target platforms (such as android-arm, android-arm64, or android-x64, ... ) or including all of those linking files because we need to support almost device types when uploading on app stores.

Please let me know if I am wrong, thank you very much !

**Comment by CaptainDario** [comment]
@loveoverflowdev why do you think this package uses platform channels?
It uses ffi as far as I know.
