### ISSUE TITLE
Error in Loading Model

### ISSUE THREAD

**Issue by Zia-Bashir** [tensorflow/flutter-tflite#23]
I'm trying to load the model for a day. I tried it around 6 months ago for object detection but that time package didn't support YOLO V8.  Now I'm trying to upload tflite mode of  esrgan-tf2 super image resolution. But the model didn't load error is coming. I double-checked everything like imports, pub, and address but I'm unable to load it. Can u please make an example that how to work with super image model 

### CONSOLE

_I/Timeline(32066): Timeline: Activity_launch_request time:451900404
I/GED     (32066): ged_boost_gpu_freq, level 100, eOrigin 2, final_idx 27, oppidx_max 27, oppidx_min 0
V/PhoneWindow(32066): DecorView setVisiblity: visibility = 4, Parent = android.view.ViewRootImpl@d044a7d, this = DecorView@333fd72[MainActivity]
2
V/PhoneWindow(32066): DecorView setVisiblity: visibility = 0, Parent = android.view.ViewRootImpl@d044a7d, this = DecorView@333fd72[MainActivity]
[log] ++++++++++ Process Image +++++++
D/skia    (32066): SkJpegCodec::onGetPixels +
D/skia    (32066): SkJpegCodec::onGetPixels -
I/flutter (32066): Error processing image: Unable to load asset: "assets/assets/model/sr_model.tflite".
I/flutter (32066): The asset does not exist or has empty data._

**Comment by Zia-Bashir** [comment]
Yes ...... And also in Pub section

**Comment by Zia-Bashir** [comment]
> I see the error message `"assets/assets/model/sr_model.tflite".`
> 
> Do you have an assets folder inside the assets folder? Just to double check :)

Yes It's okay from from pub and from assets folder

**Comment by yeikel16** [comment]
The method of loading the model from assets to y contains the asset name explicitly, so you shouldn't put it yourself.
Try removing `assets` from the path to your model.

![Captura de pantalla 2023-05-15 a la(s) 10 04 35 p m](https://github.com/tensorflow/flutter-tflite/assets/26438532/d3ac38a3-93b1-4eb8-a627-303c2fca22f5)

Try in you code:
After: `"assets/assets/model/sr_model.tflite"`
Before: `"assets/model/sr_model.tflite"`

**Comment by luiscib3r** [comment]
@Zia-Bashir, in this PR #49 I added an example for super resolution using esrgan. You can also check it in my fork https://github.com/luiscib3r/flutter-tflite/tree/develop/example/super_resolution_esrgan. Any questions, suggestions, or bug reports are welcome.

**Comment by luiscib3r** [comment]
Try with tflite_flutter: ^0.10.0

**Comment by bdytx5** [comment]
just thought i'd add, i feel most users using tflite in a mobile app will be either interested in language models or some sort of detection. I think a yolo demo/example would be awesome, and it seems like most of the groundwork has already been completed in the image classification demo!

**Comment by PaulTR** [comment]
@bdytx5 Object detection example is now in :)

**Comment by PaulTR** [comment]
Going to leave this issue open for a minute.

Action item for me: Document the new path in the wiki
