### ISSUE TITLE
The method 'UnmodifiableUint8ListView' isn't defined for the class 'Tensor'.

### ISSUE THREAD

**Issue by andresgd7** [tensorflow/flutter-tflite#232]
Im using tflite_flutter-0.10.4 but UnmodifiableUint8ListView was deprecated from typed_data some while ago:
![image](https://github.com/user-attachments/assets/24a06780-7be0-4250-984c-fa00582e0d49)

https://api.dart.dev/stable/2.13.4/dart-typed_data/dart-typed_data-library.html

When i try to run my code in android i get this:

```
../../../../AppData/Local/Pub/Cache/hosted/pub.dev/tflite_flutter-0.10.4/lib/src/tensor.dart:58:12: Error: The method 'UnmodifiableUint8ListView' isn't defined for the class 'Tensor'.
 - 'Tensor' is from 'package:tflite_flutter/src/tensor.dart' ('../../../../AppData/Local/Pub/Cache/hosted/pub.dev/tflite_flutter-0.10.4/lib/src/tensor.dart').
Try correcting the name to the name of an existing method, or defining a method named 'UnmodifiableUint8ListView'.
    return UnmodifiableUint8ListView(
```

any fix?

**Comment by ptgms** [comment]
I have a temporary fix until it is fixed in the package. Change the package locally in your pub-cache.
In the conflicting line, change the getter to this:
```
Uint8List get data {
    final data = cast<Uint8>(tfliteBinding.TfLiteTensorData(_tensor));
    return data.asTypedList(tfliteBinding.TfLiteTensorByteSize(_tensor)).asUnmodifiableView();
  }
```
That worked for me :)

**Comment by andresgd7** [comment]
Thanks bro!

**Comment by mehdigriche** [comment]
@ptgms I have shared your response on stack : https://stackoverflow.com/questions/78789213/the-method-unmodifiableuint8listview-isnt-defined-for-the-class-tensor/78842046#78842046

**Comment by CaptainDario** [comment]
Commit abac02b49b577be2853d4d6da64c7127fea7b6c8 seems to fix this, only a new version of this package is needed.

**Comment by Guziq** [comment]
The error was resolved in `0.11.0`, so I guess this can be closed.

**Comment by andresgd7** [comment]
Thanks everyone for the answers, this will be closed now.

**Comment by charlieforward9** [comment]
I am getting this error after modifying this 

```
Error (Xcode): ../../../.pub-cache/hosted/pub.dev/tflite_flutter-0.9.5/lib/src/tensor.dart:52:30: Error: The getter 'tfliteBinding' isn't defined for the class 'Tensor'.
```
