### ISSUE TITLE
The type 'TfLiteInterpreterOptions' must be 'base', 'final' or 'sealed' because the supertype 'Opaque' is 'base'.

### ISSUE THREAD

**Issue by wangcker** [tensorflow/flutter-tflite#234]
when flutter sdk upgrade to 3.24.0 ,there is a error as suject

**Comment by PaulTR** [comment]
Yes this is a known issue that I've raised with the Flutter team to see if
we can get a fix before I publish the next version to pub.dev.

**Comment by shuizhuyu1015** [comment]
When will this error be fixed?

**Comment by PaulTR** [comment]
Not sure - I ran it by the Flutter team to get some help, but everyone is pretty slammed. If someone in the community wants to work on it, that'd be awesome.
