### ISSUE TITLE
Object detection starter code not working with custom tflite model 

### ISSUE THREAD

**Issue by windspritegeorge** [tensorflow/flutter-tflite#237]
Hi there, I was able to successfully run the object detection starter code with the ssd_mobilenet tflite model. That said, when I included a custom model (properties below), it wasn't detecting my custom model, see model shape type below. Are there any quick changes to the starter code that can be made to accommodate the custom model? 

I've changed parts of the detector_service.dart code to reflect 512 and 40 too. Any help will be much appreciated. 

---------

These were the ssd_mobilelite model properties:

[log] Input Shape: [1, 300, 300, 3]
[log] Input Type: uint8
[log] Output Shape: [1, 10, 4]
[log] Output Type: float32

Custom model properties:

[log] Input Shape: [1, 512, 512, 3]
[log] Input Type: uint8
[log] Output Shape: [1, 40, 4]
[log] Output Type: float32

**Comment by chathurach** [comment]
Even if you have similar model inputs and outputs, The actual outputs and inputs can be different in arrangement and preconditioning.  You need to check input preconditions, such as normalization have been correctly done. Some models need each pixel value to be divided by 255 and some models are required to reduce 127.5 and divide by 127.5.  Try to print the output first and see if there is anything different in the output. If the normalization is incorrect, you will see some unusual results in the output (negative results, confidence with 1.00, etc.)

**Comment by windspritegeorge** [comment]
Got it, thank you! 

I eventually decided to go with code from Mediapipe as it integrated well with my model. The only downside is that I couldn't use flutter, and used kotlin / xcode instead
