### ISSUE TITLE
Pose Detection

### ISSUE THREAD

**Issue by dhirajnikam** [tensorflow/flutter-tflite#24]
Can you provide me example how to run pose detetction using this package

**Comment by PaulTR** [comment]
What model are you using and what have you tried so far?

**Comment by dhirajnikam** [comment]
https://drive.google.com/file/d/1lEXVt5g4oSfiq2rS_wAddXWriJIhAejH/view?usp=sharing

**Comment by PaulTR** [comment]
Hey @dhirajnikam, so I don't think I'm going to be able to get to that example for this repo any time soon. Your best bet for this use-case would be the ML Kit plugin for now. Thanks!

https://pub.dev/packages/google_mlkit_pose_detection
