### ISSUE TITLE
Update TensorFlowLiteC.framework download link in README 

### ISSUE THREAD

**Issue by Theunodb** [tensorflow/flutter-tflite#29]
The file at https://github.com/tensorflow/flutter-tflite/releases/download/v0.5.0/TensorFlowLiteC.framework.zip doest exist

**Comment by PaulTR** [comment]
Hi @Theunodb - can you link to the README that you're referencing? I don't see the URL in question to fix. Thanks!

**Comment by Theunodb** [comment]
Hi Paul, i see it was removed in the latest readme. It was under the **(Important) Initial setup : Add dynamic libraries to your app** section in the original readme:

iOS

Download [TensorFlowLiteC.framework](https://github.com/am15h/tflite_flutter_plugin/releases/download/v0.5.0/TensorFlowLiteC.framework.zip). For building a custom version of tensorflow, follow [instructions in wiki](https://github.com/am15h/tflite_flutter_plugin/wiki/).
Place the TensorFlowLiteC.framework in the pub-cache folder of this package.
Pub-Cache folder location: [(ref)](https://dart.dev/tools/pub/cmd/pub-get#the-system-package-cache)

~/.pub-cache/hosted/pub.dartlang.org/tflite_flutter-<plugin-version>/ios/ (Linux/ Mac)
%LOCALAPPDATA%\Pub\Cache\hosted\pub.dartlang.org\tflite_flutter-<plugin-version>\ios\ (Windows)

**Comment by PaulTR** [comment]
Ah got it - iOS instructions were going to be written by someone that updated the sample, but I'm not sure when/if that'll happen :) I'll run through this after IO to see if I can get it fixed. Thanks!

**Comment by PaulTR** [comment]
Alright link in the readme should be fixed. Reopen this if it doesn't work out for you :)
