### ISSUE TITLE
Model is not predicting as expected 

### ISSUE THREAD

**Issue by NaveenKumar-07** [tensorflow/flutter-tflite#30]
I tried using my custom model which is a binary image classification model using tflite_flutter package but it is predicting every image with incorrect label and confidence. I checked with colab, the model is **working fine**. The model's _input type_ is **Float32** and _input shape_ of the image is **28X28**. Please help me in resolving the issue here.

**Comment by PaulTR** [comment]
Hey Naveen - Did you post a sample of what you're doing anywhere? Or the model? There's not a lot to work with here for debugging :) I'll close it out for now in case you've stopped working on this project, but feel free to reopen with more details. Thanks!
