### ISSUE TITLE
Cannot run example app

### ISSUE THREAD

**Issue by glitchpop-frenzy** [tensorflow/flutter-tflite#43]
I cannot run `example` app. Seems like `main.dart`/all the necessary files for example have been deleted in [this commit](https://github.com/tensorflow/flutter-tflite/commit/06c7603c1484199e2824a0d7c1f60aef2c7fae00).

@PaulTR can't get my head around, is there any reason this was done?

**Comment by PaulTR** [comment]
They weren't deleted - they were moved down a folder in that commit.

Can you provide an example of what issues/errors you're getting so it can be debugged?

**Comment by glitchpop-frenzy** [comment]
ohhh, but why are we making different flutter projects for different classification? Wouldn't it make the example app unnecessarily large in size? since we had to load same native tensorflow-lite dependencies just for different classification.

**Comment by glitchpop-frenzy** [comment]
Okay, got it. I was thinking of since all the requeired function will be available in TFLite package then why different project fir different classification. But yes this sounds better. Thanks for the detailed explanation! 🙌🏻
