### ISSUE TITLE
Does it support mediapipe blazepose 

### ISSUE THREAD

**Issue by dhirajnikam** [tensorflow/flutter-tflite#46]
Trying to use blazepose for pose detection

**Comment by PaulTR** [comment]
If it's a tflite file, it should be useable. You'd just need to figure out the input and output data shape I think. For what it is though, we're figuring out an actual MediaPipe plugin based on what you can find [here](https://github.com/googlesamples/mediapipe/tree/main/examples).

**Comment by dhirajnikam** [comment]
[Tensor{_tensor: Pointer: address=0xb400007a3c9f8180, name: input_1, type: TfLiteType.float32, shape: [1, 256, 256, 3], data:  786432]
 [Tensor{_tensor: Pointer: address=0xb400007a3ca00920, name: Identity, type: TfLiteType.float32, shape: [1, 195], data:  780, Tensor{_tensor: Pointer: address=0xb400007a3ca00b50, name: Identity_1, type: TfLiteType.float32, shape: [1, 1], data:  4, Tensor{_tensor: Pointer: address=0xb400007a3c9ffce0, name: Identity_2, type: TfLiteType.float32, shape: [1, 256, 256, 1], data:  262144, Tensor{_tensor: Pointer: address=0xb400007a3c9ffd50, name: Identity_3, type: TfLiteType.float32, shape: [1, 64, 64, 39], data:  638976, Tensor{_tensor: Pointer: address=0xb400007a3ca00a00, name: Identity_4, type: TfLiteType.float32, shape: [1, 117], data:  468]
 
 
 This is input and output shape

**Comment by PaulTR** [comment]
Got it - I don't actually have an answer here. I'd probably hold off on that one until the MediaPipe plugin is started :)
