### ISSUE TITLE
 The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (TensorFlowLiteSwift)

### ISSUE THREAD

**Issue by fuhaixiao** [tensorflow/flutter-tflite#48]
I followed the iOS Initial setup  to placed `TensorFlowLiteC.framework` in `~/.pub-cache/hosted/pub.dartlang.org/tflite_flutter-<plugin-version>/ios/`, 
then ran ` pod update` in the ios folder and output " The 'Pods-Runner' target has transitive dependencies that include statically linked binaries: (TensorFlowLiteSwift)" .

What am I doing wrong?

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.0, on macOS 13.3.1 22E772610a darwin-arm64, locale
    zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.2)
[✓] VS Code (version 1.78.2)

**Comment by FahadAhmed721** [comment]
I am also stuck the same issue. Even I am not finding this tflite_flutter folder inside pub.dartlang

**Comment by supratikkoley** [comment]
Any update on this???

**Comment by ViaJables** [comment]
Stuck on this as well, couldn't get the folder to show up in pub.dartlang but a dart pub cache clean and repair caused it to show up in the pub.dev folder. Adding the library to the appropriate folder there, nor trying any combination of solutions online has gotten the error to go away.

**Comment by unifractal** [comment]
I am seeing the same issue, i'm on an M2 mac, so the previous versions have proven to be difficult to run as well.

**Comment by ChangJoo-Park** [comment]
Same issue here.

**Comment by luiscib3r** [comment]
Try with tflite_flutter: ^0.10.0. All dependencies are downloaded using CocoaPod, you do not need to download or include any TensorFlow build in your application.

**Comment by fuhaixiao** [comment]
@luiscib3r it works! thanks for you great job!
