### ISSUE TITLE
Remove `assets` prefix when load model from assets

### ISSUE THREAD

**Issue by luiscib3r** [tensorflow/flutter-tflite#51]
The method of loading the model from the assets already contains the asset name explicitly, so you shouldn't put it yourself. Try removing `assets` from the path to your model.

![Captura de pantalla 2023-05-15 a la(s) 10 04 35 p m](https://github.com/tensorflow/flutter-tflite/assets/26438532/d3ac38a3-93b1-4eb8-a627-303c2fca22f5)

Try in you code:
After: `"assets/assets/model/sr_model.tflite"`
Before: `"assets/model/sr_model.tflite"`

_Originally posted by @yeikel16 in https://github.com/tensorflow/flutter-tflite/issues/23#issuecomment-1548862353_

Adding the assets prefix when loading the model causes confusion #23. Also, you may want to place the model in another folder than `assets`. Maybe in the `models` folder as example.

**Comment by luiscib3r** [comment]
I'm going to fix this in pr #49

**Comment by yeikel16** [comment]
great, thanks for the help !!
