### ISSUE TITLE
Failed to lookup symbol in Archived (ios) build

### ISSUE THREAD

**Issue by supratikkoley** [tensorflow/flutter-tflite#53]
While trying to run the app in archive mode (downloaded from testflight) on iOS, getting this below error -

**Failed to lookup symbol 'TfLiteModelCreateFromFile': dlsym (RTLD_DEFAULT, TfLiteModelCreateFromFile): symbol not found** 

Can anyone please help into this?

using latest version of the plugin:
**tflite_flutter: ^0.9.5**

**Comment by luiscib3r** [comment]
Try with tflite_flutter: ^0.10.0

**Comment by DaDummy** [comment]
Just a wild guess, but did you follow the best practice for embedding native code using ffi?

https://docs.flutter.dev/platform-integration/ios/c-interop#open-source-third-party-library

The line declaring the `source_files` appears to be commented out in the project's podspec.

**Comment by DaDummy** [comment]
To be clear: I am facing this issue with `tflite_flutter: ^0.10.0`

**Comment by DaDummy** [comment]
Looks like this is an instance of https://github.com/flutter/flutter/issues/62666 which was resolved by documenting a workaround: https://docs.flutter.dev/platform-integration/ios/c-interop#stripping-ios-symbols

Solution:

> 1.  In Xcode, go to Target Runner > Build Settings > Strip Style.
> 2.  Change from All Symbols to Non-Global Symbols.

**Comment by DaDummy** [comment]
I'd recommend adding this to the Setup steps in readme and on pub.dev

**Comment by PaulTR** [comment]
Updated in #76. Will aim to publish 0.10.1 today, which will include updating the readme on pub.dev.

Thanks for tracking that down!
