### ISSUE TITLE
Interpreter.fromAsset fail to load asset in 0.10.0

### ISSUE THREAD

**Issue by 2channelkrt** [tensorflow/flutter-tflite#58]
Interpreter.fromAsset fails to load asset despite it's under assets/ and is defined in pubspec.yaml

this worked fine in 0.9.5,

**Comment by luiscib3r** [comment]
Add 'assets/' to your Interpreter.fromAssets. Example: `interpreter = await Interpreter.fromAsset( 'assets/perceptron.tflite');`

**Comment by 2channelkrt** [comment]
thanks. i didn't have to add 'assets/' in 0.9.5 but now it works.
