### ISSUE TITLE
Need new version of flutter-tflite for tensorflow 2.x converted models

### ISSUE THREAD

**Issue by tharhtetsan** [tensorflow/flutter-tflite#59]
I converted my model to `.onnx` version with  `onnxruntime 1.14.1` and then I converted `.onnx `model to `.tflite` model with `tensorflow 2.10.1` and .  This models can inference on python with no problem.  But when we test with flutter-tflite with it show unsupported version.

**Comment by PaulTR** [comment]
Have you tried to run your model natively on Android or iOS to help isolate the issue? I have a feeling it's more an issue with that onnx conversion than the plugin, but would want to verify with the flutter layer of complexity removed.

**Comment by tharhtetsan** [comment]
Thank you @PaulTR  for your reply and contribution. 
Yes I tried my model natively convert without onnx, but it only show unsupported version.
but I have not tried with 26 April, 2023 Update. I will tell back here, when I tested.

**Comment by PaulTR** [comment]
Did you ever get a chance to test this?
