### ISSUE TITLE
IOS: App crashing when building ad-hoc version for firebase App Distribution

### ISSUE THREAD

**Issue by Thou94** [tensorflow/flutter-tflite#62]
Hi, when I run the app locally on a ios device everything works great. But if I build it with `flutter build ipa --export-method=ad-hoc` for firebase App Distribution and download the app, then the App crashes as soon as tflite plugin gets triggered.
In the older version of this package, I think it was 0.9.0, I didn't had any problems to run the ipa via firebase.
I would really appreciate your help.

This is the error message, which I get from firebase crashlytics:

> EXC_BAD_ACCESS (KERN_INVALID_ADDRESS)

> Crashed: com.apple.main-thread
0  ???                            0x1c75b2cd4 (Fehlt)
1  ???                            0x10610ccf4 (Fehlt)
2  ???                            0x10610ccf4 (Fehlt)
3  ???                            0x10610cee4 (Fehlt)
4  ???                            0x106108fd0 (Fehlt)
5  Runner                         0x80d0 +[GeneratedPluginRegistrant registerWithRegistry:] + 133 (GeneratedPluginRegistrant.m:133)
6  Runner                         0x8440 AppDelegate.application(_:didFinishLaunchingWithOptions:) + 11 (AppDelegate.swift:11)
7  Runner                         0x8708 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) (<compiler-generated>)
8  ???                            0x1cf867888 (Fehlt)
9  ???                            0x1cf866fac (Fehlt)
10 ???                            0x1cf865f88 (Fehlt)
11 ???                            0x1cf865bd4 (Fehlt)
12 ???                            0x1cf5ab600 (Fehlt)
13 ???                            0x1cf8ed918 (Fehlt)
14 ???                            0x1cf79dfa4 (Fehlt)
15 ???                            0x1cf79ddcc (Fehlt)
16 ???                            0x1cf79d97c (Fehlt)
17 ???                            0x1cf79d848 (Fehlt)
18 ???                            0x1cfe7ffa8 (Fehlt)
19 ???                            0x1cff18f98 (Fehlt)
20 ???                            0x1cf649958 (Fehlt)
21 ???                            0x1cfabc7a8 (Fehlt)
22 ???                            0x1cf71c0b8 (Fehlt)
23 ???                            0x1cf71bf28 (Fehlt)
24 ???                            0x1cf71b47c (Fehlt)
25 ???                            0x1cf71b208 (Fehlt)
26 ???                            0x1e2f75500 (Fehlt)
27 ???                            0x1e2fb451c (Fehlt)
28 ???                            0x1e2f79294 (Fehlt)
29 ???                            0x1e2fb4154 (Fehlt)
30 ???                            0x1d4929fdc (Fehlt)
31 ???                            0x1d492da5c (Fehlt)
32 ???                            0x1e2f833b0 (Fehlt)
33 ???                            0x1e2f82f4c (Fehlt)
34 ???                            0x1e2f8572c (Fehlt)
35 ???                            0x1cd425f54 (Fehlt)
36 ???                            0x1cd43232c (Fehlt)
37 ???                            0x1cd3b6270 (Fehlt)
38 ???                            0x1cd3cbba8 (Fehlt)
39 ???                            0x1cd3d0ed4 (Fehlt)
40 ???                            0x2066ce368 (Fehlt)
41 ???                            0x1cf8af3d0 (Fehlt)
42 ???                            0x1cf8af034 (Fehlt)
43 Runner                         0x8880 main + 6 (AppDelegate.swift:6)
44 ???                            0x1eba38960 (Fehlt)

> com.google.firebase.crashlytics.startup
0  ???                            0x209f4dadc (Fehlt)
1  ???                            0x1d492a5f4 (Fehlt)
2  ???                            0x1d492abf4 (Fehlt)
3  ???                            0x1059ef780 (Fehlt)
4  ???                            0x105a04670 (Fehlt)
5  ???                            0x1d4929fdc (Fehlt)
6  ???                            0x1d492b828 (Fehlt)
7  ???                            0x105a041d0 (Fehlt)
8  ???                            0x1059d4474 (Fehlt)
9  ???                            0x105a040c8 (Fehlt)
10 ???                            0x1059e7d68 (Fehlt)
11 ???                            0x1059e7430 (Fehlt)
12 ???                            0x105a03138 (Fehlt)
13 ???                            0x105a0289c (Fehlt)
14 FBLPromises                    0x8c48 (Fehlt UUID a9e2820bb798337ca26c3e580903c949)
15 FBLPromises                    0x84f0 (Fehlt UUID a9e2820bb798337ca26c3e580903c949)
16 ???                            0x1d49284b4 (Fehlt)
17 ???                            0x1d4929fdc (Fehlt)
18 ???                            0x1d4931774 (Fehlt)
19 ???                            0x1d49321e0 (Fehlt)
20 ???                            0x1d493ce10 (Fehlt)
21 ???                            0x21a3afdf8 (Fehlt)
22 ???                            0x21a3afb98 (Fehlt)

> com.apple.UIKit.KeyboardManagement
0  ???                            0x209f4e680 (Fehlt)
1  ???                            0x1d492a9cc (Fehlt)
2  ???                            0x1d492a780 (Fehlt)
3  ???                            0x1d4939860 (Fehlt)
4  ???                            0x1d493940c (Fehlt)
5  ???                            0x1cf8af6a4 (Fehlt)
6  ???                            0x1cd3c4704 (Fehlt)
7  ???                            0x1cd370b6c (Fehlt)
8  ???                            0x1c77d1b08 (Fehlt)
9  ???                            0x1c77a2ef0 (Fehlt)
10 ???                            0x1c7d7c2e4 (Fehlt)
11 ???                            0x21a410f1c (Fehlt)
12 ???                            0x21a403fb4 (Fehlt)
13 ???                            0x1d492a05c (Fehlt)
14 ???                            0x1d4947f58 (Fehlt)
15 ???                            0x1d493156c (Fehlt)
16 ???                            0x1d4932214 (Fehlt)
17 ???                            0x1d493ce10 (Fehlt)
18 ???                            0x21a3afdf8 (Fehlt)
19 ???                            0x21a3afb98 (Fehlt)

> com.google.firebase.crashlytics.ios.binary-images
0  ???                            0x209f4e974 (Fehlt)
1  ???                            0x1cd403614 (Fehlt)
2  ???                            0x1cd3e51f8 (Fehlt)
3  ???                            0x1cd3abd84 (Fehlt)
4  ???                            0x1cd39e20c (Fehlt)
5  ???                            0x1cd3e5090 (Fehlt)
6  ???                            0x1cd3aa324 (Fehlt)
7  ???                            0x1c7749a80 (Fehlt)
8  ???                            0x1c7749a08 (Fehlt)
9  ???                            0x1c77499d4 (Fehlt)
10 ???                            0x1059d6d18 (Fehlt)
11 ???                            0x1059d6b70 (Fehlt)
12 ???                            0x1059d67c0 (Fehlt)
13 ???                            0x1d49284b4 (Fehlt)
14 ???                            0x1d4929fdc (Fehlt)
15 ???                            0x1d4931694 (Fehlt)
16 ???                            0x1d49321e0 (Fehlt)
17 ???                            0x1d493ce10 (Fehlt)
18 ???                            0x21a3afdf8 (Fehlt)
19 ???                            0x21a3afb98 (Fehlt)

> com.apple.uikit.eventfetch-thread
0  ???                            0x209f4db48 (Fehlt)
1  ???                            0x209f60008 (Fehlt)
2  ???                            0x209f60248 (Fehlt)
3  ???                            0x209f4e08c (Fehlt)
4  ???                            0x1cd3caaf0 (Fehlt)
5  ???                            0x1cd3cbd34 (Fehlt)
6  ???                            0x1cd3d0ed4 (Fehlt)
7  ???                            0x1c7772334 (Fehlt)
8  ???                            0x1c777221c (Fehlt)
9  ???                            0x1cf9e433c (Fehlt)
10 ???                            0x1c778b808 (Fehlt)
11 ???                            0x21a3b06cc (Fehlt)
12 ???                            0x21a3afba4 (Fehlt)

> Thread
0  ???                            0x209f4e050 (Fehlt)
1  ???                            0x21a3afe44 (Fehlt)
2  ???                            0x21a3afb98 (Fehlt)

> Thread
0  ???                            0x209f4e050 (Fehlt)
1  ???                            0x21a3afe44 (Fehlt)
2  ???                            0x21a3afb98 (Fehlt)

> Thread
0  ???                            0x209f4e050 (Fehlt)
1  ???                            0x21a3afe44 (Fehlt)
2  ???                            0x21a3afb98 (Fehlt)

> com.google.firebase.crashlytics.MachExceptionServer
0  ???                            0x1059fe39c (Fehlt)
1  ???                            0x1059fd65c (Fehlt)
2  ???                            0x1059fd7ac (Fehlt)
3  ???                            0x1059fd53c (Fehlt)
4  ???                            0x1059eebe8 (Fehlt)
5  ???                            0x1059f2ce8 (Fehlt)
6  ???                            0x1059f28d0 (Fehlt)
7  ???                            0x1059f2514 (Fehlt)
8  ???                            0x21a3b06cc (Fehlt)
9  ???                            0x21a3afba4 (Fehlt)

**Comment by PaulTR** [comment]
That's a new one to me. I'll reach out to the FlutterFire people next week when I'm back at the office to see what we can figure out.

**Comment by Thou94** [comment]
If you need more informations, please let me know what exactly you need.

**Comment by Thou94** [comment]
I could solve the issue with this solution: [https://github.com/dart-lang/ffi/issues/41#issuecomment-845139183](url)

**Comment by PaulTR** [comment]
Just to verify - you're good now yeah? If so I'll go over that thread and try to get a post written for helping others. Thanks!

**Comment by Thou94** [comment]
Yes, everything runs perfectly.

**Comment by PaulTR** [comment]
Awesome!

**Comment by vladRudenua23** [comment]
> I could solve the issue with this solution: [https://github.com/dart-lang/ffi/issues/41#issuecomment-845139183](url)

Can you send a solution here?
