### ISSUE TITLE
Expand Dims in Flutter-TfLite for Image Classification

### ISSUE THREAD

**Issue by MinSiThu** [tensorflow/flutter-tflite#68]
# How to expand_dims in flutter tflite

I am making an image classification app.

My tflite model has **input shape = (1,244,244,3)**
After reading image from image picker, and load as TensorImage, my image shape is **(244,244,3)**.

When I put the image to run in the interpreter 
```dart
_model.interpreter.run(inputTensorImage.buffer, outputBuffer.buffer);
```
Following error occurs.
**StateError (Bad state: failed precondition)**

How can I change my image dimension **(244,244,3)** into **(1,244,244,3)** in flutter-tflite?

**Comment by gregorscholz** [comment]
Just put the input inside `[ ]`. 
You can also see this in the given example [here](https://github.com/tensorflow/flutter-tflite/blob/7d8f4ff2ca75a93235446208794a75d391df00f9/example/image_classification_mobilenet/lib/main.dart#L146).

**Comment by MinSiThu** [comment]
For other searching for solution, here is a gist of code.

#### How to expand dims in flutter-tflite

```dart
final imageMatrix = List.generate(
        imageInput.height,
        (y) => List.generate(
          imageInput.width,
          (x) {
            final pixel = imageInput.getPixel(x, y);
            return [pixel.r, pixel.g, pixel.b];
          },
        ),
      );

newMatrix = [imageMatrix];
```
