### ISSUE TITLE
 No podspec found for `flutter_tflite` in `.symlinks/plugins/flutter_tflite/ios

### ISSUE THREAD

**Issue by faizanmehar** [tensorflow/flutter-tflite#72]
No podspec found for `flutter_tflite` in `.symlinks/plugins/flutter_tflite/ios

**Comment by PaulTR** [comment]
Hey @faizanmehar, I'm going to need a lot more detail. What were you trying to do? Were you running one of the examples?

**Comment by PaulTR** [comment]
Closing out since I hadn't heard an update - hoping it's worked out as I haven't seen other similar issues posted.

**Comment by Sums-shadow** [comment]
Same issue, anyone found solution?
