### ISSUE TITLE
Camera

### ISSUE THREAD

**Issue by ptiszai** [tensorflow/flutter-tflite#78]
Will you make a sample program with a camera?
Thank.

**Comment by gregorscholz** [comment]
Checkout [this](https://github.com/tensorflow/flutter-tflite/tree/main/example/image_classification_mobilenet) or [this](https://github.com/tensorflow/flutter-tflite/tree/main/example/object_detection_ssd_mobilenet) example.

**Comment by ptiszai** [comment]
Thank.
