### ISSUE TITLE
ERROR: tensorflow/lite/kernels/concatenation.cc:159 t->dims->data[d] != t0->dims->data[d] (1 != 2)

### ISSUE THREAD

**Issue by azazadev** [tensorflow/flutter-tflite#80]
Hi,

I convert my model from ONNX to TensorFlow and I'm using the image_classification_mobilenet example to test it with flutter-tflite plugin, but I have this error

tensorflow/lite/kernels/concatenation.cc:159 t->dims->data[d] != t0->dims->data[d] (1 != 2)
ERROR: tensorflow/lite/kernels/concatenation.cc:159 t->dims->data[d] != t0->dims->data[d] (1 != 2)
Node number 6 (CONCATENATION) failed to prepare.
ERROR: Node number 6 (CONCATENATION) failed to prepare.
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: Bad state: failed precondition
#0      checkState (package:quiver/check.dart:74:5)
#1      Interpreter.allocateTensors (package:tflite_flutter/src/interpreter.dart:156:5)
#2      Interpreter.runInference (package:tflite_flutter/src/interpreter.dart:204:7)
#3      Interpreter.runForMultipleInputs (package:tflite_flutter/src/interpreter.dart:180:5)
#4      Interpreter.run (package:tflite_flutter/src/interpreter.dart:172:5)
#5      _HomeState.runInference (package:myproject/main.dart:151:17)
#6      _HomeState.processImage (package:myproject/main.dart:137:7)
#7      _HomeState.build.<anonymous closure> (package:myproject/main.dart:257:23)
<asynchronous suspension>

[✓] Flutter (Channel stable, 3.10.2, on macOS 13.1 22C65 darwin-arm64, locale en-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 2021.1)
[✓] IntelliJ IDEA Community Edition (version 2022.3.1)
[✓] VS Code (version 1.78.1)
[✓] Connected device (1 available)
[✓] Network resources

• No issues found!

any idea please ?

**Comment by azazadev** [comment]
output should match the output of interpreter

**Comment by kapil708** [comment]
@azazadev Have you found any solution?

**Comment by azazadev** [comment]
> @azazadev Did you find any solution?

When I posted this, I lacked experience in model and image processing. Please ensure the input and output formats of your model match your provided data. Additionally, could you print out the model's input and output specifications along with the image preprocessing code? This could help in identifying the issue.
