### ISSUE TITLE
Unhandled Exception: Invalid argument(s): Failed to lookup symbol 'TfLiteGpuDelegateV2Create': undefined symbol: TfLiteGpuDelegateV2Create

### ISSUE THREAD

**Issue by madmouse17** [tensorflow/flutter-tflite#83]
![Cuplikan layar 2023-06-07 221450](https://github.com/tensorflow/flutter-tflite/assets/33163281/d54f4cd6-e903-4964-93bf-eb4f12f93ee0)

how can i resolve?
please help me.

Android - real device

**Comment by madmouse17** [comment]
I use jnilibs new it's error like above,  but I'm use jnilibs old it's working normally

**Comment by ayyysh04** [comment]
i am getting the same error for GpuDelegate() (not v2) in ^0.10.0 ,how did u changed the jni lib as after 0.9.0 ,jni libs are installed automatically by the gradle
