### ISSUE TITLE
Extract class and score from result

### ISSUE THREAD

**Issue by azazadev** [tensorflow/flutter-tflite#88]
Hi,

I'm able to run my tflite model using this amazing plugin, but I'm not able to extract result, I'm using the same image_classification_mobilenet [example](https://github.com/tensorflow/flutter-tflite/blob/main/example/image_classification_mobilenet/lib/main.dart) with small update of output to match my model

my code is :  

```
final input = [imageMatrix];
final output = [
  List.generate(
    21,
    (index) => List.filled(7098, 0.0),
  )
];

// Run inference
interpreter.run(input, output);

final result = output.first;
```

when I debug the result variable the value is :

```
index 0 : [1.4157819747924805, 2.1544673442840576, ...... ] : size = 7098

index 1 : [1.805556058883667, 1.946408987045288, ........ ] : size = 7098

index 2 : [1.0974576473236084, 1.980888843536377, ....... ] : size = 7098
...
...
index 20 : [0.0024664357770234, 0.007526415400207, ...... ] : size = 7098
```

my question : how I can extract the label and score from the result ?

**NOTE** : the same model with same image as test give me class 3 and score of 0.88 in original python code
Thanks

**Comment by PaulTR** [comment]
Hey, sorry I've been traveling for I/O Connect and fell a little behind. Are you still seeing this issue? If so, can you put your sample on GitHub somewhere and I can try running it to see if I can duplicate the issue?

Thanks!

**Comment by azazadev** [comment]
Finally I'm able to resolve my issue, Apologies I forget to close issue, Thanks @PaulTR for this amazing package !

**Comment by azazadev** [comment]
close ticket as this error is probably due to wrong model after conversion from onnx to tflite

**Comment by azazadev** [comment]
Hi @PaulTR I open the issue again as I close this before because I'm able to progress with another model, but new one is very slow ( more the 200 ms to process 1 image ), this is why I'm back to original model that take around 50ms to process 1 image but I'm not able to extract score and class from output result :(

this is code [sample](https://github.com/azazadev/flutter-tflite-fazaza/blob/main/example/object_detection_ssd_mobilenet/lib/main.dart) to run ( in this example when you click on Test correct image button this should return score > 0.7 )


NOTE : as this model is converted from onnx, this is how onnx model is processed to extract score and class from output reesult in python [link](https://github.com/azazadev/NARUTO-HandSignDetection/blob/48ddd9ff74a0b468cd8ed85ba9773f47936b6b01/model/yolox/yolox_onnx.py#L54)

**Comment by azazadev** [comment]
add example

**Comment by ambujjain86** [comment]
@azazadev were you able to extract the class and score from the tensor output;

**Comment by azazadev** [comment]
> @azazadev were you able to extract the class and score from the tensor output;

no, not from this one, now I'm using another mode
