### ISSUE TITLE
Error (Xcode): Undefined symbol: _TfLiteInterpreterGetSignatureCount

### ISSUE THREAD

**Issue by faizin4107** [tensorflow/flutter-tflite#95]
after updating to the latest version of tflite_flutter, i experienced this while running ios, tflite_flutter: ^0.10.1,
can anyone help?

**Comment by PaulTR** [comment]
Hey @faizin4107 - do you see this on the samples as well? I'm wondering if you've been able to isolate where this is triggering.

**Comment by PaulTR** [comment]
Closing out due to inactivity and being unable to reproduce the issue.
