### ISSUE TITLE
runForMultipleInputs is slower

### ISSUE THREAD

**Issue by azazadev** [tensorflow/flutter-tflite#97]
I'm trying to run image classification on a live camera feed, and I observe slowness on runForMultipleInputs, more then **200ms** for 1 image!,  it's normal ? 

```
  List<List<Object>> _runInference(ByteBuffer byteBuffer) {
    final output = {
      0: [List<List<num>>.filled(10, List<num>.filled(4, 0))],
      1: [List<num>.filled(10, 0)],
      2: [List<num>.filled(10, 0)],
      3: [0.0],
    };
    _interpreter!.runForMultipleInputs([byteBuffer], output);
    print(_interpreter?.lastNativeInferenceDurationMicroSeconds.toString()); ---> more then 200ms
    ....
   ...
  }
```

NOTE : 
- I remove interpreterOptions.addDelegate(GpuDelegate()) as with this option the app crash 
- I'm working on master branch, so I have the fix of [listEquals](https://github.com/tensorflow/flutter-tflite/pull/85)

Device : Iphone 11

**Comment by PaulTR** [comment]
That shouldn't be normal - the underlying classification should happen the same way regardless when it's given the data in the same format. My gut says it's likely a thread issue blocking the camera feed, but I can't confirm with the information provided.

**Comment by VadymPinchuk** [comment]
@azazadev you can check my PR, I have created for liveImageStream processing. There is a lot of code, as it is a complete app, but I am sure you can find detector_service there to compare the logic. It works as smooth as it could be. Also it contains some metrics for inference speed. and many other useful stuff. Please check it

**Comment by azazadev** [comment]
> @azazadev you can check my PR, I have created for liveImageStream processing. There is a lot of code, as it is a complete app, but I am sure you can find detector_service there to compare the logic. It works as smooth as it could be. Also it contains some metrics for inference speed. and many other useful stuff. Please check it

Thanks @VadymPinchuk , I will try this next week and provide feedback

**Comment by azazadev** [comment]
@VadymPinchuk  I test with your code, model processing is still taking more then 200 ms but now there is no lag in camera stream when I'm using detector_service !, good work !!!

**Comment by VadymPinchuk** [comment]
@azazadev I would love to ask for clarity, is that the whole process takes more than 200 ms, or just detection part? ( from the point when tflite received input/output tensors and till results were provided) ? Thank you for providing more clarity.

**Comment by azazadev** [comment]
> @azazadev I would love to ask for clarity, is that the whole process takes more than 200 ms, or just detection part? ( from the point when tflite received input/output tensors and till results were provided) ? Thank you for providing more clarity.

example when I'm running app on real Device Iphone11

conversion from camera to Image  : 47 ms
Resize Image : 7 ms
convert resized Image to ByteListFloat32  : 7 ms
save Image  : 65 ms
runForMultipleInputs : 135 ms

**totalElapsedTime: 261**

**Comment by VadymPinchuk** [comment]
@azazadev Thanks for sharing this metrics. It would be also great if you could share at least one screenshot or video to gif from your iPhone with latest metrics and detection in action. 
As I see you are using old version, where I left image saving for debug purposes. That was needed for better understanding of the process. While now it is not needed for realtime detection purposes.

What about total elapsed time - it is fine, to have these numbers, as we are doing lots of manipulations before the actual detection. Metrics are very average I would say.

**Comment by azazadev** [comment]
> @azazadev Thanks for sharing this metrics. It would be also great if you could share at least one screenshot or video to gif from your iPhone with latest metrics and detection in action. As I see you are using old version, where I left image saving for debug purposes. That was needed for better understanding of the process. While now it is not needed for realtime detection purposes.
> 
> What about total elapsed time - it is fine, to have these numbers, as we are doing lots of manipulations before the actual detection. Metrics are very average I would say.

saveImage removed, so now all taking 200ms ( 160 ms of time in model processing ), anyway I'm working on other model that can take less time ( 60 ms ) , but facing some issue on image preprocessing ... I'm completely new on ML, flutter .... :)
